### ISSUE TITLE
New release for pyfolio

### ISSUE THREAD

**Issue by eigenfoo** [quantopian/pyfolio#414]
It looks like [enough has changed](https://github.com/quantopian/pyfolio/compare/v0.7.0...master) on pyfolio to merit v0.8.0 (with risk and performance attribution, I think we might even want to call it v1.0.0!)

We are also seeing an increasing number of users running into bugs that have already been patched: upping the version would make it easier to diagnose errors (both ours, and open source users).

To-do:
- [ ] Performance attribution tear sheet #417 (still WIP, will definitely want to wait for this)
- [ ] Resolve any dependency issues with zipline/alphalens/empyrical
- [x] Do we want to outsource Fama-French functionality from pyfolio to empyrical? [#56 on empyrical](https://github.com/quantopian/empyrical/pull/56) (Answer: yes. PR waiting: #416)
- [ ] Do we want to include returns decomposition from alphalens into pyfolio? [#183 on alphalens](https://github.com/quantopian/alphalens/pull/183)

@twiecki @gusgordon @richafrank @Jstauth thoughts? If this sounds good I'll organize a milestone :)

## New features
- Risk tear sheet: added a new tear sheet to analyze risk exposures to common factors, sector, market cap and illiquidity (#391) 
- Simple tear sheet: added a new tear sheet that presents only the most important plots in the full tear sheet, for a quick general overview of a portfolio's performance (#389) 
- Volatility plot: added a rolling annual volatility plot in the returns tear sheet (#390) 

## Bugfixes
- Fixed bug regarding Yahoo API and pandas data reader (#395)
- Removed `information_ratio` to remain [compatible with empyrical](https://github.com/quantopian/pyfolio/commit/a34222e6a065b85147e9e7e53cce4549058bd51e) 
- Fama-French rolling multivariate regression bug fix (#406)

## Maintenance
- Updated and improved jupyter notebook documentation (#411)

**Comment by twiecki** [comment]
Yes, should absolutely cut a new release! Want to do a PR that updates the version number?

**Comment by georgh0021** [comment]
I'll draft a release and organize a milestone so we know what PRs to wait for and what not to. A milestone will be better than an issue :)

**Comment by eigenfoo** [comment]
I just remembered @twiecki I had drafted a new release announcement on github, but since my access has been revoked I assume its lost. You can just use my comment above to draft a new one.

**Comment by twiecki** [comment]
Nothing should get lost. It's either on a branch you pushed or on a local branch of yours. Where did you keep it?

**Comment by eigenfoo** [comment]
As a draft release: click "10 releases" on the info bar on the pyfolio github home page.

**Comment by eigenfoo** [comment]
@twiecki @gusgordon once @vikram-narayan's perf attributions are done we can cut a new version of pyfolio

**Comment by twiecki** [comment]
We can probably already do that now given the changes and refactorings we have.

**Comment by eigenfoo** [comment]
If you think that would be a good idea! 🎉

**Comment by twiecki** [comment]
@eigenfoo Want to do a PR with the release announcements and version bump to `0.8.0`?

**Comment by eigenfoo** [comment]
Will do!

**Comment by bonesmccoy** [comment]
Hi, isn't the changes of requirements breaking the requirements of zipline 1.1.1

zipline 1.1.1 : pandas==0.18.1
pyfolio 0.8.0: pandas>=0.19.0

zipline 1.1.1: empyrical==0.2.2
pyfolio 0.8.0: empyrical>=0.3.2

Source:
Pyfolio: https://github.com/quantopian/pyfolio/blob/v0.8.0/setup.py
Zipline: https://github.com/quantopian/zipline/blob/1.1.1/etc/requirements.txt

you may say: you don't need ZL with pyfolio. 
Yes but when I'm trying to open a zipline result pickle file, if I don't have ZL Pyfolio is not able to unserialize the ZL Objects.

Am I doing something wrong?
Any suggestion?

**Comment by twiecki** [comment]
@bonesmccoy Hm, that's indeed a pickle (no pun intended). The empyrical version mismatch should be fixed easily, the pandas one might be more tricky. CC @richafrank

**Comment by twiecki** [comment]
We can probalby make pyfolio pandas 0.18.1 compat without too much effort (if it isn't already).

**Comment by richafrank** [comment]
Yup, we'll be fixing the [pandas issue](https://github.com/quantopian/pyfolio/issues/407) soon, unless you get to it first. 

zipline doesn't read the reqs.txt literally and actually supports empyrical>=2.2, so I don't think that's an issue here, unless you specifically want to use empyrical<0.3.2.

**Comment by eigenfoo** [comment]
Closed by #552
